name: Test
"on":
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test_matrix:
    strategy:
      matrix:
        node-version:
          - '14.17'
          - 16
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - run: git config --global user.name github-actions
      - run: git config --global user.email github-actions@github.com
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v2
        with:
          node-version: "${{ matrix.node-version }}"
          cache: npm
      - run: yarn ci
      - name: Ensure dependencies are compatible with the version of node
        run: npx ls-engines
      - run: "yarn test:ci"
  test:
    runs-on: ubuntu-latest
    needs: test_matrix
    steps:
      - uses: actions/checkout@v2
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v2
        with:
          node-version: "${{ matrix.node-version }}"
          cache: npm
      - run: yarn ci
      - run: yarn lint
